// ข้อมูลจำลองสำหรับอสังหาริมทรัพย์
export const properties = [
  {
    id: 1,
    title: "SKYLINE CONDO",
    location: "สุขุมวิท - อโศก",
    price: "30,000 บาท / เดือน",
    isRent: true,
    isSale: false,
    bedrooms: 1,
    bathrooms: 1,
    area: 35,
    description: "คอนโดหรูใจกลางเมือง ใกล้ BTS อโศก และ MRT สุขุมวิท เดินทางสะดวก มีสิ่งอำนวยความสะดวกครบครัน",
    features: ["สระว่ายน้ำ", "ฟิตเนส", "รักษาความปลอดภัย 24 ชม.", "ที่จอดรถ"],
    image: "/images/property-1.png",
  },
  {
    id: 2,
    title: "SKYLINE CONDO",
    location: "พร้อมพงษ์ - ทองหล่อ",
    price: "5,000,000 บาท",
    isRent: false,
    isSale: true,
    bedrooms: 2,
    bathrooms: 2,
    area: 65,
    description: "คอนโดหรูย่านทองหล่อ ตกแต่งสวย เฟอร์นิเจอร์ครบ วิวสวย ใกล้ BTS ทองหล่อ",
    features: ["สระว่ายน้ำ", "ฟิตเนส", "สวนหย่อม", "ห้องประชุม"],
    image: "/images/property-2.png",
  },
  {
    id: 3,
    title: "SKYLINE CONDO",
    location: "รัชดา - ห้วยขวาง",
    price: "30,000 บาท / เดือน",
    isRent: true,
    isSale: false,
    bedrooms: 1,
    bathrooms: 1,
    area: 40,
    description: "คอนโดใหม่ย่านรัชดา ใกล้ MRT ห้วยขวาง เดินทางสะดวก ห้องสวย วิวดี",
    features: ["สระว่ายน้ำ", "ฟิตเนส", "ซาวน่า", "ห้องสมุด"],
    image: "/images/property-3.png",
  },
  {
    id: 4,
    title: "SKYLINE CONDO",
    location: "สาทร - นราธิวาส",
    price: "5,000,000 บาท",
    isRent: false,
    isSale: true,
    bedrooms: 2,
    bathrooms: 2,
    area: 70,
    description: "คอนโดหรูย่านธุรกิจ ใกล้ BTS ช่องนนทรี วิวแม่น้ำเจ้าพระยา ตกแต่งสวย",
    features: ["สระว่ายน้ำ", "ฟิตเนส", "สวนลอยฟ้า", "ร้านสะดวกซื้อ"],
    image: "/images/property-4.png",
  },
  {
    id: 5,
    title: "SKYLINE CONDO",
    location: "ลาดพร้าว - เซ็นทรัล",
    price: "30,000 บาท / เดือน",
    isRent: true,
    isSale: false,
    bedrooms: 1,
    bathrooms: 1,
    area: 35,
    description: "คอนโดใกล้เซ็นทรัลลาดพร้าว เดินทางสะดวก ใกล้ MRT ลาดพร้าว ห้องสวย",
    features: ["สระว่ายน้ำ", "ฟิตเนส", "สวนหย่อม", "รักษาความปลอดภัย 24 ชม."],
    image: "/images/property-5.png",
  },
  {
    id: 6,
    title: "SKYLINE CONDO",
    location: "อ่อนนุช - บางนา",
    price: "30,000 บาท / เดือน",
    isRent: true,
    isSale: false,
    bedrooms: 1,
    bathrooms: 1,
    area: 32,
    description: "คอนโดใกล้ BTS อ่อนนุช เดินทางสะดวก ใกล้ห้างสรรพสินค้า ห้องสวย",
    features: ["สระว่ายน้ำ", "ฟิตเนส", "สวนหย่อม", "รักษาความปลอดภัย 24 ชม."],
    image: "/images/property-1.png",
  },
  {
    id: 7,
    title: "SKYLINE CONDO",
    location: "พระราม 9 - RCA",
    price: "5,000,000 บาท",
    isRent: false,
    isSale: true,
    bedrooms: 2,
    bathrooms: 2,
    area: 60,
    description: "คอนโดใกล้ MRT พระราม 9 เดินทางสะดวก ใกล้ห้างสรรพสินค้า ห้องสวย",
    features: ["สระว่ายน้ำ", "ฟิตเนส", "สวนหย่อม", "รักษาความปลอดภัย 24 ชม."],
    image: "/images/property-2.png",
  },
  {
    id: 8,
    title: "SKYLINE CONDO",
    location: "จตุจักร - หมอชิต",
    price: "30,000 บาท / เดือน",
    isRent: true,
    isSale: false,
    bedrooms: 1,
    bathrooms: 1,
    area: 35,
    description: "คอนโดใกล้ BTS หมอชิต และ MRT จตุจักร เดินทางสะดวก ใกล้ตลาดนัดจตุจักร",
    features: ["สระว่ายน้ำ", "ฟิตเนส", "สวนหย่อม", "รักษาความปลอดภัย 24 ชม."],
    image: "/images/property-3.png",
  },
  {
    id: 9,
    title: "SKYLINE CONDO",
    location: "พญาไท - อนุสาวรีย์",
    price: "5,000,000 บาท",
    isRent: false,
    isSale: true,
    bedrooms: 2,
    bathrooms: 2,
    area: 65,
    description: "คอนโดใกล้ BTS อนุสาวรีย์ เดินทางสะดวก ใกล้ห้างสรรพสินค้า ห้องสวย",
    features: ["สระว่ายน้ำ", "ฟิตเนส", "สวนหย่อม", "รักษาความปลอดภัย 24 ชม."],
    image: "/images/property-4.png",
  },
  {
    id: 10,
    title: "SKYLINE CONDO",
    location: "บางซื่อ - ประชาชื่น",
    price: "30,000 บาท / เดือน",
    isRent: true,
    isSale: false,
    bedrooms: 1,
    bathrooms: 1,
    area: 35,
    description: "คอนโดใกล้ MRT บางซื่อ เดินทางสะดวก ใกล้ห้างสรรพสินค้า ห้องสวย",
    features: ["สระว่ายน้ำ", "ฟิตเนส", "สวนหย่อม", "รักษาความปลอดภัย 24 ชม."],
    image: "/images/property-5.png",
  },
  {
    id: 11,
    title: "SKYLINE CONDO",
    location: "สุขุมวิท - อโศก",
    price: "5,000,000 บาท",
    isRent: false,
    isSale: true,
    bedrooms: 2,
    bathrooms: 2,
    area: 65,
    description: "คอนโดหรูใจกลางเมือง ใกล้ BTS อโศก และ MRT สุขุมวิท เดินทางสะดวก",
    features: ["สระว่ายน้ำ", "ฟิตเนส", "รักษาความปลอดภัย 24 ชม.", "ที่จอดรถ"],
    image: "/images/property-1.png",
  },
  {
    id: 12,
    title: "SKYLINE CONDO",
    location: "พร้อมพงษ์ - ทองหล่อ",
    price: "30,000 บาท / เดือน",
    isRent: true,
    isSale: false,
    bedrooms: 1,
    bathrooms: 1,
    area: 35,
    description: "คอนโดหรูย่านทองหล่อ ตกแต่งสวย เฟอร์นิเจอร์ครบ วิวสวย ใกล้ BTS ทองหล่อ",
    features: ["สระว่ายน้ำ", "ฟิตเนส", "สวนหย่อม", "ห้องประชุม"],
    image: "/images/property-2.png",
  },
  {
    id: 13,
    title: "SKYLINE CONDO",
    location: "รัชดา - ห้วยขวาง",
    price: "5,000,000 บาท",
    isRent: false,
    isSale: true,
    bedrooms: 2,
    bathrooms: 2,
    area: 70,
    description: "คอนโดใหม่ย่านรัชดา ใกล้ MRT ห้วยขวาง เดินทางสะดวก ห้องสวย วิวดี",
    features: ["สระว่ายน้ำ", "ฟิตเนส", "ซาวน่า", "ห้องสมุด"],
    image: "/images/property-3.png",
  },
  {
    id: 14,
    title: "SKYLINE CONDO",
    location: "สาทร - นราธิวาส",
    price: "30,000 บาท / เดือน",
    isRent: true,
    isSale: false,
    bedrooms: 1,
    bathrooms: 1,
    area: 35,
    description: "คอนโดหรูย่านธุรกิจ ใกล้ BTS ช่องนนทรี วิวแม่น้ำเจ้าพระยา ตกแต่งสวย",
    features: ["สระว่ายน้ำ", "ฟิตเนส", "สวนลอยฟ้า", "ร้านสะดวกซื้อ"],
    image: "/images/property-4.png",
  },
  {
    id: 15,
    title: "SKYLINE CONDO",
    location: "ลาดพร้าว - เซ็นทรัล",
    price: "5,000,000 บาท",
    isRent: false,
    isSale: true,
    bedrooms: 2,
    bathrooms: 2,
    area: 65,
    description: "คอนโดใกล้เซ็นทรัลลาดพร้าว เดินทางสะดวก ใกล้ MRT ลาดพร้าว ห้องสวย",
    features: ["สระว่ายน้ำ", "ฟิตเนส", "สวนหย่อม", "รักษาความปลอดภัย 24 ชม."],
    image: "/images/property-5.png",
  },
  {
    id: 16,
    title: "SKYLINE CONDO",
    location: "อ่อนนุช - บางนา",
    price: "5,000,000 บาท",
    isRent: false,
    isSale: true,
    bedrooms: 2,
    bathrooms: 2,
    area: 65,
    description: "คอนโดใกล้ BTS อ่อนนุช เดินทางสะดวก ใกล้ห้างสรรพสินค้า ห้องสวย",
    features: ["สระว่ายน้ำ", "ฟิตเนส", "สวนหย่อม", "รักษาความปลอดภัย 24 ชม."],
    image: "/images/property-1.png",
  },
  {
    id: 17,
    title: "SKYLINE CONDO",
    location: "พระราม 9 - RCA",
    price: "30,000 บาท / เดือน",
    isRent: true,
    isSale: false,
    bedrooms: 1,
    bathrooms: 1,
    area: 35,
    description: "คอนโดใกล้ MRT พระราม 9 เดินทางสะดวก ใกล้ห้างสรรพสินค้า ห้องสวย",
    features: ["สระว่ายน้ำ", "ฟิตเนส", "สวนหย่อม", "รักษาความปลอดภัย 24 ชม."],
    image: "/images/property-2.png",
  },
  {
    id: 18,
    title: "SKYLINE CONDO",
    location: "จตุจักร - หมอชิต",
    price: "5,000,000 บาท",
    isRent: false,
    isSale: true,
    bedrooms: 2,
    bathrooms: 2,
    area: 65,
    description: "คอนโดใกล้ BTS หมอชิต และ MRT จตุจักร เดินทางสะดวก ใกล้ตลาดนัดจตุจักร",
    features: ["สระว่ายน้ำ", "ฟิตเนส", "สวนหย่อม", "รักษาความปลอดภัย 24 ชม."],
    image: "/images/property-3.png",
  },
  {
    id: 19,
    title: "SKYLINE CONDO",
    location: "พญาไท - อนุสาวรีย์",
    price: "30,000 บาท / เดือน",
    isRent: true,
    isSale: false,
    bedrooms: 1,
    bathrooms: 1,
    area: 35,
    description: "คอนโดใกล้ BTS อนุสาวรีย์ เดินทางสะดวก ใกล้ห้างสรรพสินค้า ห้องสวย",
    features: ["สระว่ายน้ำ", "ฟิตเนส", "สวนหย่อม", "รักษาความปลอดภัย 24 ชม."],
    image: "/images/property-4.png",
  },
  {
    id: 20,
    title: "SKYLINE CONDO",
    location: "บางซื่อ - ประชาชื่น",
    price: "5,000,000 บาท",
    isRent: false,
    isSale: true,
    bedrooms: 2,
    bathrooms: 2,
    area: 65,
    description: "คอนโดใกล้ MRT บางซื่อ เดินทางสะดวก ใกล้ห้างสรรพสินค้า ห้องสวย",
    features: ["สระว่ายน้ำ", "ฟิตเนส", "สวนหย่อม", "รักษาความปลอดภัย 24 ชม."],
    image: "/images/property-5.png",
  },
]

// ข้อมูลจำลองสำหรับเมืองยอดนิยม
export const cities = [
  {
    id: 1,
    name: "กรุงเทพ",
    image: "/images/bangkok.png",
    properties: 1250,
  },
  {
    id: 2,
    name: "เชียงใหม่",
    image: "/images/chiangmai.png",
    properties: 450,
  },
  {
    id: 3,
    name: "ภูเก็ต",
    image: "/images/phuket.png",
    properties: 320,
  },
]

// ข้อมูลจำลองสำหรับโครงการที่แนะนำ
export const featuredProperty = {
  id: 100,
  title: "THE GRAND RESIDENCE",
  location: "สุขุมวิท - อโศก",
  price: "เริ่มต้น 5.2 ล้านบาท",
  type: "4ชั้น ดูเพล็กซ์",
  area: "27.5-32 ตร.ม.",
  units: "157 ยูนิต (ทั้งหมด)",
  description: "โครงการบ้านหรู ตั้งอยู่ใจกลางเมืองใกล้รถไฟฟ้า สิ่งอำนวยความสะดวกครบครัน",
  features: ["ใกล้รถไฟฟ้า", "สระว่ายน้ำ", "ฟิตเนส", "รักษาความปลอดภัย 24 ชม.", "ที่จอดรถ"],
  image: "/images/featured-property.png",
}
